# -*- coding: utf-8 -*-
"""data_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HN5xASDGYTCMA6qDhPavTd3qQESN6jvE

Dataset Module - Started: 13-03-2025 | Completed: 13-03-2025

This module demonstrates modularity and abstraction by encapsulating CSV data loading into a reusable function, promoting code reusability and maintainability.
"""

def import_dataset(dataset_path):

    dataset = []

    try:
        with open(dataset_path, 'r', encoding="utf-8") as data_file:
            # Read the first line (headers)
            columns = data_file.readline().strip().split(',')

            # Read the remaining lines and store each as a dictionary
            for line in data_file:
                values = line.strip().split(',')
                row_data = dict(zip(columns, values))  # Create dictionary from column names
                dataset.append(row_data)  # Add the row dictionary to the list

        dictList = {index: value for index, value in enumerate(dataset)}#convert list into dict
        return dictList  # Returns a list of dictionaries

    except FileNotFoundError:
        print(f"Error: File '{dataset_path}' not found.")
        return None
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

#from google.colab import files
#files.upload()

#ls #to show all uploaded files in this workplace

#import_dataset('data1.csv')

